# Site settings
title: "Sander en Maud"
description: 16 oktober 2021

    
owner: Sander Aernouts
first_published: 2018
email: vittorio.monaco1@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.sabrinaevittoriosposi.it" # the base hostname & protocol for your site

# Google analytics
google_analytics: "UA-40721189-2"

social:
  github: https://github.com/vittoriom/wedding-site

# Build settings
markdown: kramdown
